### ISSUE TITLE
paper-time-picker-edit-dialog should use same input as output format

### ISSUE THREAD

**Issue by ronnyroeller** [Collaborne/paper-date-picker-item#1]
The element `paper-time-picker-edit-dialog` expects as input a property `time` of type `String`. As output it generates an event with a parameter `time` of type `Object`.

For an editor, the Input and output format should be the same to simplify the life of the consumer. This leads to these options:
1. Both `Date` (which would be my preferred option in the given context as this moves the whole complexity to the edit-dialog instead of the consumer of the dialog)
2. Both `Object`
3. Both `String`

**Comment by cminardi** [comment]
Both date picker and datetime picker now work with Date object.

Fixed in: 9686b2e
