### ISSUE TITLE
Wrong use of paper-styles causing warnings

### ISSUE THREAD

**Issue by jroosing** [Collaborne/paper-date-picker-item#10]
paper-date-picker-item.html uses the following import:

`<link rel="import" href="../paper-styles/paper-styles.html">`
This causes iron-flex-layout/classes/\* to be imported, that contains deprecated things. such as /deep/

An easy fix is to replace 
`<link rel="import" href="../paper-styles/paper-styles.html">`
with:
`<link rel="import" href="../iron-flex-layout/iron-flex-layout-classes.html">`

and 
`<paper-ripple fit></paper-ripple>`
with
`<paper-ripple class="fit"></paper-ripple>`

Because from what I could see, only "fit" was being used. 
It removes deprecation warnings and makes it a bit more future proof.

**Comment by ankon** [comment]
For future reference: fixed by https://github.com/Collaborne/paper-date-picker-item/pull/11
