### ISSUE TITLE
Remove code duplication

### ISSUE THREAD

**Issue by ronnyroeller** [Collaborne/paper-date-picker-item#2]
There is lots of code duplication between `paper-date-picker-item` and `paper-datetime-picker-item` as well as between `paper-date-picker-edit-dialog` and `paper-time-picker-edit-dialog`.

Please move the shared properties and methods to shared behaviors.

See this video for further information on Polymer behaviors: https://www.youtube.com/watch?v=YrlmieL3Z0k&index=18&list=PLOU2XLYxmsII5c3Mgw6fNYCzaWrsM3sMN

Documentation is here: https://www.polymer-project.org/1.0/docs/devguide/behaviors.html

**Comment by cminardi** [comment]
Duplicated code has been exported to external behavior.

Fixed in: 4c8b27d

**Comment by ronnyroeller** [comment]
Please test the behavior on its own instead of duplicating the test within derived elements (e.g. "format date behavior").
See the tests for `iron-behaviors` on how to create a test element with the behavior and then testing that one: https://github.com/PolymerElements/iron-behaviors/tree/master/test

**Comment by cminardi** [comment]
Thanks! Fixed in 07894e6 61fa178 and 298c799

Edit: the linked commits have formatting issues, those have also been fixed.
