### ISSUE TITLE
Add tests for datetime-picker

### ISSUE THREAD

**Issue by ronnyroeller** [Collaborne/paper-date-picker-item#3]
Please add tests to check datetime-picker behavior. This might also simplify the refactoring for issue #2.

Check this video fordetails: https://www.youtube.com/watch?v=YBNBr9ECXLo&index=2&list=PLOU2XLYxmsII5c3Mgw6fNYCzaWrsM3sMN
See also existing (insufficient) tests for date-picker: https://github.com/Collaborne/paper-date-picker-item/tree/master/test

**Comment by cminardi** [comment]
Added tests for datetime-picker, and improved test coverage for simple date-picker
