### ISSUE TITLE
Strange style at opening

### ISSUE THREAD

**Issue by diegohaz** [Collaborne/paper-date-picker-item#5]
Using Chrome 47, when the modal dialog pops up it has this appearance for some milliseconds.

<img width="723" alt="screen shot 2015-12-30 at 16 53 18" src="https://cloud.githubusercontent.com/assets/3068563/12055638/4350e0a2-af16-11e5-8693-9a15ec562734.png">

**Comment by ronnyroeller** [comment]
@diegohaz Thanks for reporting. The new 1.0.15 release might help.
Unfortunately, I failed to reproduce the issue. Hence I can't really test it myself.
Could you please try if this resolves the problem for you?

**Comment by diegohaz** [comment]
The problem still happens. I can reproduce it on demo page.

I think the problem is actually with `paper-date-picker`. If it's inside a `paper-dialog` with an `entry-animation`, it breaks. I could also reproduce this on `paper-date-picker` demo, just by adding any `entry-animation`. https://github.com/bendavis78/paper-date-picker/issues/66

Well, a quick fix would be just removing the `entry-animation`. We can also wait for `neon-animation-finish` to display the date picker.

**Comment by ronnyroeller** [comment]
Thanks for the info.
I implemented the quick fix (remove animation) and create a new release 1.0.16.
Feel free to provide a PR for the `neon-animation-finish` if you prefer that solution.
