### ISSUE TITLE
Switch back to upstream versions

### ISSUE THREAD

**Issue by ankon** [Collaborne/paper-date-picker-item#8]
Marker bug, depending on:

https://github.com/bendavis78/paper-time-picker/issues/28
https://github.com/bendavis78/paper-date-picker/issues/74
https://github.com/bendavis78/moment-element/pull/1

**Comment by ronnyroeller** [comment]
Fixed by https://github.com/Collaborne/paper-date-picker-item/commit/789289e130bb3bba5f4a7492924d5b9519f86f76
